let answer;
let test;
let Sunday;
let Monday;
let Tuesday;
let Wednesday;
let Thursday;
let Friday;
let Sabbath;
let Sunday1;
let Monday1;
let Tuesday1;
let Wednesday1;
let Thursday1;
let Friday1;
let Sabbath1;
let Sundayfin;
let Mondayfin;
let Tuesdayfin;
let Wednesdayfin;
let Thursdayfin;
let Fridayfin;
let Sabbathfin;

window.addEventListener("DOMContentLoaded", displayAns);

async function displayAns() {
  const response = await fetch("http://localhost:8000/results");
  answer = await response.text();
  test = answer.replace(/\\n/g, "");
  Sunday = test.indexOf("Menu for Sunday");
  Monday = test.indexOf("Menu for Monday");
  Tuesday = test.indexOf("Menu for Tuesday");
  Wednesday = test.indexOf("Menu for Wednesday");
  Thursday = test.indexOf("Menu for Thursday");
  Friday = test.indexOf("Menu for Friday");
  Sabbath = test.indexOf("Menu for Sabbath");
  Sunday1 = test.indexOf("The Deli at the Village Market");
  Monday1 = test.indexOf("The Deli at the Village Market", Sunday1 + 1);
  Tuesday1 = test.indexOf("The Deli at the Village Market", Monday1 + 1);
  Wednesday1 = test.indexOf("The Deli at the Village Market", Tuesday1 + 1);
  Thursday1 = test.indexOf("The Deli at the Village Market", Wednesday1 + 1);
  Friday1 = test.indexOf("The Deli at the Village Market", Thursday1 + 1);
  Sabbath1 = test.indexOf("The Deli at the Village Market", Friday1 + 1);
  Sundayfin = test.slice(Sunday, Sunday1);
  Mondayfin = test.slice(Monday, Monday1);
  Tuesdayfin = test.slice(Tuesday, Tuesday1);
  Wednesdayfin = test.slice(Wednesday, Wednesday1);
  Thursdayfin = test.slice(Thursday, Thursday1);
  Fridayfin = test.slice(Friday, Friday1);
  Sabbathfin = test.slice(Sabbath, Sabbath1);
  document.getElementById("Sunday").innerHTML = Sundayfin;
  document.getElementById("Monday").innerHTML = Mondayfin;
  document.getElementById("Tuesday").innerHTML = Tuesdayfin;
  document.getElementById("Wednesday").innerHTML = Wednesdayfin;
  document.getElementById("Thursday").innerHTML = Thursdayfin;
  document.getElementById("Friday").innerHTML = Fridayfin;
  document.getElementById("Sabbath").innerHTML = Sabbathfin;
}
